### ISSUE TITLE
can't get v14.0.0, module source tree too large

### ISSUE THREAD

**Issue by amanibhavam** [cdktf/cdktf-provider-aws-go#4]
I can't `go get` v14.0.0 of this module.   I can get v13.0.0, but I need v14.0.0 for CDKTF 0.16.0

I'm using go 1.20.3, on macOS and Linux, arm64.

```
$ go get github.com/cdktf/cdktf-provider-aws-go/aws/v14
go: downloading github.com/cdktf/cdktf-provider-aws-go/aws/v14 v14.0.1
go: github.com/cdktf/cdktf-provider-aws-go/aws/v14: create zip: module source tree too large (max size is 524288000 bytes)
```

**Comment by ansgarm** [comment]
Hi @amanibhavam 👋

Thank you for reporting this! We'll track this in our main repository: https://github.com/hashicorp/terraform-cdk/issues/2829
